from typing import Optional
from pydantic import BaseModel, Field

class Roles(BaseModel):
    MarketingTechnologist: Optional[str] = Field(default=None, description="select if given skills matches with Project management, HTML, CSS, Google Analytics, Email marketing platforms")
    SEOSpecialist: Optional[str] = Field(default=None, description="select if given skills matches with Search engine optimization, Keyword research, Google Analytics, Content strategy")
    WebAnalyticsDeveloper: Optional[str] = Field(default=None, description="select if given skills matches with Data analysis, JavaScript, Google Analytics, Tag management systems")
    DigitalMarketingManager: Optional[str] = Field(default=None, description="select if given skills matches with Online marketing strategies, Social media marketing, Content creation, Analytics")
    SocialMediaManager: Optional[str] = Field(default=None, description="select if given skills matches with Social media platforms, Content creation, Community engagement, Analytics")
    GrowthHacker: Optional[str] = Field(default=None, description="select if given skills matches with Marketing strategies, Data analysis, A/B testing, User acquisition")
    ContentManager: Optional[str] = Field(default=None, description="select if given skills matches with Content creation, Editing, SEO, Content strategy")
    ContentStrategist: Optional[str] = Field(default=None, description="select if given skills matches with Content planning, SEO, Audience research, Editorial guidelines")
    InformationArchitect: Optional[str] = Field(default=None, description="select if given skills matches with User experience design, Wireframing, Information organization, Usability testing")
    UXDesigner: Optional[str] = Field(default=None, description="select if given skills matches with User research, Wireframing, Prototyping, Usability testing")
    UIDesigner: Optional[str] = Field(default=None, description="select if given skills matches with Visual design, Typography, Color theory, Prototyping tools")
    AccessibilitySpecialist: Optional[str] = Field(default=None, description="select if given skills matches with Web accessibility standards, Assistive technologies, User testing, Inclusive design")
    InteractionDesigner: Optional[str] = Field(default=None, description="select if given skills matches with User interaction design, Prototyping, Usability testing, Animation")
    FrontEndDesigner: Optional[str] = Field(default=None, description="select if given skills matches with HTML, CSS, JavaScript, Responsive design")
    FrontEndDeveloper: Optional[str] = Field(default=None, description="select if given skills matches with HTML, CSS, JavaScript, Frameworks like React or Angular")
    MobileDeveloper: Optional[str] = Field(default=None, description="select if given skills matches with Mobile app development, iOS or Android platforms, Swift or Kotlin programming")
    FullStackDeveloper: Optional[str] = Field(default=None, description="select if given skills matches with Front-end technologies, Back-end technologies, Databases, Server management")
    SoftwareDeveloper: Optional[str] = Field(default=None, description="select if given skills matches with Programming languages, Software development methodologies, Problem-solving")
    WordPressDeveloper: Optional[str] = Field(default=None, description="select if given skills matches with PHP, WordPress CMS, Theme and plugin development, HTML, CSS")
    FrameworksSpecialist: Optional[str] = Field(default=None, description="select if given skills matches with Specific frameworks expertise, Best practices, Integration methods")
    ReactDeveloper: Optional[str] = Field(default=None, description="select if given skills matches with React.js, JavaScript, Component-based architecture, State management")
    PythonDeveloper: Optional[str] = Field(default=None, description="select if given skills matches with Python programming, Web frameworks like Django or Flask, Data manipulation")
    ThreeDDesigner: Optional[str] = Field(default=None, description="select if given skills matches with 3D modeling, Rendering software, Animation, Spatial design")
    ARVRDeveloper: Optional[str] = Field(default=None, description="select if given skills matches with Augmented reality, Virtual reality, 3D modeling, Programming languages like C#")
    GameDeveloper: Optional[str] = Field(default=None, description="select if given skills matches with Game design principles, Programming languages, Game engines like Unity or Unreal")
    AugmentedRealityDesigner: Optional[str] = Field(default=None, description="select if given skills matches with AR design principles, 3D modeling, User interaction design")
    VirtualRealityDesigner: Optional[str] = Field(default=None, description="select if given skills matches with VR design principles, 3D environments, User experience design")
    BusinessSystemsAnalyst: Optional[str] = Field(default=None, description="select if given skills matches with Business analysis, System design, Data modeling, Stakeholder communication")
    SystemsEngineer: Optional[str] = Field(default=None, description="select if given skills matches with System architecture, Integration, Performance tuning, Troubleshooting")
    SystemsAdministrator: Optional[str] = Field(default=None, description="select if given skills matches with Server management, Network configuration, Security protocols, User support")
    AIDeveloper: Optional[str] = Field(default=None, description="select if given skills matches with Artificial intelligence, Machine learning, Programming languages like Python, Data analysis")
    AlgorithmEngineer: Optional[str] = Field(default=None, description="select if given skills matches with Algorithm design, Data structures, Optimization techniques, Programming")
    MachineLearningEngineer: Optional[str] = Field(default=None, description="select if given skills matches with Machine learning models, Data preprocessing, Statistical analysis, Programming")
    DatabaseAdministrator: Optional[str] = Field(default=None, description="select if given skills matches with Database management, SQL, Performance tuning, Backup and recovery")
    DataArchitect: Optional[str] = Field(default=None, description="select if given skills matches with Data modeling, Database design, ETL processes, Big data technologies")
    DataModeler: Optional[str] = Field(default=None, description="select if given skills matches with Data analysis, Data modeling tools, Database design, Normalization techniques")
    DataAnalyst: Optional[str] = Field(default=None, description="select if given skills matches with Data interpretation, Statistical analysis, Visualization tools, Excel")
    DataScientist: Optional[str] = Field(default=None, description="select if given skills matches with Statistical modeling, Machine learning, Data visualization, Programming languages like R or Python")
    CloudArchitect: Optional[str] = Field(default=None, description="select if given skills matches with Cloud computing platforms, Infrastructure design, Security protocols, Scalability planning")
    TechnicalLead: Optional[str] = Field(default=None, description="select if given skills matches with Team leadership, Project management, Technical expertise, Mentoring")
    DevOpsManager: Optional[str] = Field(default=None, description="select if given skills matches with Continuous integration, Deployment strategies, Infrastructure automation, Team coordination")
    AgileProjectManager: Optional[str] = Field(default=None, description="select if given skills matches with Agile methodologies, Scrum framework, Project planning, Stakeholder communication")
    ProductManager: Optional[str] = Field(default=None, description="select if given skills matches with Product lifecycle management, Market research, Strategic planning, Cross-functional coordination")
    TechnicalAccountManager: Optional[str] = Field(default=None, description="select if given skills matches with Client relationship management, Technical support, Product knowledge, Problem-solving")
    SecuritySpecialist: Optional[str] = Field(default=None, description="select if given skills matches with Cybersecurity protocols, Risk assessment, Incident response, Compliance standards")
    QASpecialist: Optional[str] = Field(default=None, description="select if given skills matches with Testing methodologies, Bug tracking, Automation tools, Attention to detail")
    ComputerGraphicsAnimator: Optional[str] = Field(default=None, description="select if given skills matches with Animation software, Storyboarding, 3D modeling, Visual storytelling")
    MobileAppDeveloper: Optional[str] = Field(default=None, description="select if given skills matches with Mobile platforms, App development frameworks, User interface design, Programming languages")
    MobileAppDesigner: Optional[str] = Field(default=None, description="select if given skills matches with Mobile design principles, User experience, Prototyping, Visual design")